// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Status_MicroService.Entities;

#nullable disable

namespace Status_MicroService.Migrations
{
    [DbContext(typeof(StatusDBContext))]
    [Migration("20240221182849_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Status_MicroService.Entities.Status", b =>
                {
                    b.Property<Guid>("IdStatusa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BacklogItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("VrednostStatusa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdStatusa");

                    b.HasIndex("BacklogItemId")
                        .IsUnique();

                    b.ToTable("Status");

                    b.HasData(
                        new
                        {
                            IdStatusa = new Guid("4e4bbba9-9dbe-4f8d-847a-310e08d26de5"),
                            BacklogItemId = new Guid("4e4bbba9-9dbe-4f8d-847a-310e08d26de2"),
                            VrednostStatusa = "Done"
                        },
                        new
                        {
                            IdStatusa = new Guid("b293a04a-2900-48b4-9b1c-a6f3455aa8d5"),
                            BacklogItemId = new Guid("4e4bbba9-9dbe-4f8d-847a-310e08d26de9"),
                            VrednostStatusa = "Done"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
