// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Projekat_Microservice.Data;

#nullable disable

namespace Projekat_Microservice.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20240214225731_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Projekat_Microservice.Models.Projekat", b =>
                {
                    b.Property<Guid>("ProjekatID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DatumProjekta")
                        .HasColumnType("datetime2");

                    b.Property<string>("NazivProjekta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OpisProjekta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TimID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ProjekatID");

                    b.ToTable("Projekat");
                });
#pragma warning restore 612, 618
        }
    }
}
